// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBpob4tdAGhcGYjarz3yaDzabqSg-NzjI',
    appId: '1:581677715365:web:4c1c11f9c933a22cde224c',
    messagingSenderId: '581677715365',
    projectId: 'talabat-9f2cd',
    authDomain: 'talabat-9f2cd.firebaseapp.com',
    storageBucket: 'talabat-9f2cd.firebasestorage.app',
    measurementId: 'G-EHTZS8X95Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6J3KyTSpBmAXcG-cgMBZDJ5mxi4FBE3w',
    appId: '1:581677715365:android:11c916b8cc8302a2de224c',
    messagingSenderId: '581677715365',
    projectId: 'talabat-9f2cd',
    storageBucket: 'talabat-9f2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz8h821voUmKh5KQ8DfFHC55wWF7JqqCU',
    appId: '1:581677715365:ios:12f68b827c8ecc84de224c',
    messagingSenderId: '581677715365',
    projectId: 'talabat-9f2cd',
    storageBucket: 'talabat-9f2cd.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz8h821voUmKh5KQ8DfFHC55wWF7JqqCU',
    appId: '1:581677715365:ios:12f68b827c8ecc84de224c',
    messagingSenderId: '581677715365',
    projectId: 'talabat-9f2cd',
    storageBucket: 'talabat-9f2cd.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBpob4tdAGhcGYjarz3yaDzabqSg-NzjI',
    appId: '1:581677715365:web:dd32df7266debac1de224c',
    messagingSenderId: '581677715365',
    projectId: 'talabat-9f2cd',
    authDomain: 'talabat-9f2cd.firebaseapp.com',
    storageBucket: 'talabat-9f2cd.firebasestorage.app',
    measurementId: 'G-PXRM5M0Y1J',
  );
}
